package com.yls.projects.robot.entity;

import java.util.Date;

/**
 * 资源实体类
 * 
 * @author Alex Lee 李璐
 * @date 2018年5月6日下午4:49:00
 */
public class DialogResource {
    /** 资源id主键 */
    private String resourceId;

    /** 资源名称 */
    private String resourceName;

    /** 父id */
    private String parentId;

    /** 排序 */
    private Long sort;

    /** 跳转href */
    private String href;

    /** 图标 */
    private String icon;

    /** 是否展示 */
    private String isShow;

    /** 权限标识 */
    private String permission;

    /** 备注 */
    private String remark;

    /** 创建者 */
    private String createBy;

    /** 创建时间 */
    private Date createDate;

    /** 更新者 */
    private String updateBy;

    /** 更新时间 */
    private Date updateDate;

    /** 删除标记。0-正常，1-已删除 */
    private String delFlag;

   
    @Override
	public String toString() {
		return "DialogResource [resourceId=" + resourceId + ", resourceName=" + resourceName + ", parentId=" + parentId
				+ ", sort=" + sort + ", href=" + href + ", icon=" + icon + ", isShow=" + isShow + ", permission="
				+ permission + ", remark=" + remark + ", createBy=" + createBy + ", createDate=" + createDate
				+ ", updateBy=" + updateBy + ", updateDate=" + updateDate + ", delFlag=" + delFlag + "]";
	}

	public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.resource_id
     *
     * @param resourceId the value for dialog_resource.resource_id
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.resource_name
     *
     * @return the value of dialog_resource.resource_name
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.resource_name
     *
     * @param resourceName the value for dialog_resource.resource_name
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.parent_id
     *
     * @return the value of dialog_resource.parent_id
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.parent_id
     *
     * @param parentId the value for dialog_resource.parent_id
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.sort
     *
     * @return the value of dialog_resource.sort
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.sort
     *
     * @param sort the value for dialog_resource.sort
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.href
     *
     * @return the value of dialog_resource.href
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.href
     *
     * @param href the value for dialog_resource.href
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.icon
     *
     * @return the value of dialog_resource.icon
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.icon
     *
     * @param icon the value for dialog_resource.icon
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.is_show
     *
     * @return the value of dialog_resource.is_show
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.is_show
     *
     * @param isShow the value for dialog_resource.is_show
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.permission
     *
     * @return the value of dialog_resource.permission
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.permission
     *
     * @param permission the value for dialog_resource.permission
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.remark
     *
     * @return the value of dialog_resource.remark
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.remark
     *
     * @param remark the value for dialog_resource.remark
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.create_by
     *
     * @return the value of dialog_resource.create_by
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.create_by
     *
     * @param createBy the value for dialog_resource.create_by
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.create_date
     *
     * @return the value of dialog_resource.create_date
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.create_date
     *
     * @param createDate the value for dialog_resource.create_date
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.update_by
     *
     * @return the value of dialog_resource.update_by
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.update_by
     *
     * @param updateBy the value for dialog_resource.update_by
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.update_date
     *
     * @return the value of dialog_resource.update_date
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.update_date
     *
     * @param updateDate the value for dialog_resource.update_date
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialog_resource.del_flag
     *
     * @return the value of dialog_resource.del_flag
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialog_resource.del_flag
     *
     * @param delFlag the value for dialog_resource.del_flag
     *
     * @mbggenerated Sun May 06 11:40:42 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}